### ISSUE TITLE
Typo in Assignment#2: NameError in test case

### ISSUE THREAD

**Issue by jorgeluisgalarraga** [AASD4011-2023-spring/aasd4011-2023-spring#14]
There is a typo on the unit test for the implemented method to test the calculate_matrix_product() 
 
![image](https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/assets/55800648/e8981cda-57b5-4d60-9441-9c5d7a18c306)

The line of code above is calling a method that hasn't been implemented. It should call the calculate_matrix_product(X, W)

**Comment by sakshamprakash01** [comment]
This is indeed a typo, thanks for bringing it up!

Explanation: 
I believe this test function was meant to ensure that the function `calculate_matrix_product()` actually FAILS for input matrices having dimensions which are not allowed for multiplication.

Fixes:
1. While `calculate_product()` is indeed a type and should infact be `calculate_matrix_product()`,
2. another fix is the type of `Exception` to be considered i.e. the line above it. Instead of handling all possible Exceptions, it should only test for `RuntimeError`.

The fix has been made into [PR#3](https://github.com/AASD4011-2023-spring/aasd4011-assignment2-tensors/pull/3) on the assignment repo.
